# Generated by Django 4.1.5 on 2024-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dimensions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
